core/urls.py
from django.urls import path
from . import views
from photographer import views as photographer_views

app_name = "core"

urlpatterns = [
    path("", photographer_views.HomeView.as_view(), name="home")
]

photographer/urls.py
from django.urls import path
from . import views

app_name = "photographers"

urlpatterns = [
    path("create/", views.ApplyZzigsaView.as_view(), name="create"),
    path("<int:pk>", views.PhotographerDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditPhotographerView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.PhotographerPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:photographer_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo"),
]

zzigsaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("user/", include("user.urls", namespace="user")),
    path("photographers/", include("photographer.urls", namespace="photographers")),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photographer/models.py
from django.db import models
from django.urls import reverse
from core import models as core_models
# Create your models here.

class Photo(core_models.TimeStampedModel):

    """ Photo Model Definition """

    file = models.ImageField(upload_to="portfolio")
    zzigsa = models.ForeignKey("Photographer", related_name="photos", on_delete=models.CASCADE)


class Photographer(core_models.TimeStampedModel):

    """ Photographer Model Definition """

    zzigsa = models.ForeignKey("user.User", related_name="photographer", on_delete=models.CASCADE)
    introduction = models.CharField(max_length=150)
    title = models.CharField(max_length=80)
    description = models.TextField()
    location = models.CharField(max_length=140)
    equip = models.CharField(max_length=100)
    equip_picture = models.ImageField(upload_to="equip", blank=True)
    sns = models.URLField(blank=True)
    profile = models.ImageField(upload_to="profile", blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photographers:detail', kwargs={'pk': self.pk})

    def first_photo(self):
        photo, = self.photos.all()[:1]
        return photo.file.url

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        return photos

photographer/forms.py
from django import forms
from . import models


class CreatePhotoForm(forms.ModelForm):

    class Meta:
        model = models.Photo
        fields = ("file",)

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        photographer = models.Photographer.objects.get(pk=pk)
        photo.photographer = photographer
        photo.save()


class ApplyZzigsaForm(forms.ModelForm):
    class Meta:
        model = models.Photographer
        fields = (
            "introduction",
            "title",
            "description",
            "location",
            "equip",
            "equip_picture",
            "sns",
            "profile",
        )

    def save(self, *args, **kwargs):
        photographer = super().save(commit=False)
        photographer.zzigsa.zzigsa = "Not yet"
        photographer.save()

photographer/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView, UpdateView, FormView
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from user import mixins as user_mixins
from . import models, forms

# Create your views here.
class HomeView(ListView):

    """ HomeView Definition """

    model = models.Photographer
    paginate_by = 10
    # paginate_orphans = ??
    ordering = "created"
    context_object_name = "photographers"




class PhotographerDetail(DetailView):
    
    """ Photographer Detail Definition """

    model = models.Photographer


class EditPhotographerView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Photographer
    template_name = "photographer/photographer_edit.html"
    fields = (
        "introduction",
        "title",
        "description",
        "location",
        "equip",
        "equip_picture",
        "sns",
        "profile",
    )
    
    def get_object(self, queryset=None):
        photographer = super().get_object(queryset=queryset)
        if photographer.zzigsa.pk != self.request.user.pk:
            raise Http404
        return photographer


class PhotographerPhotosView(user_mixins.LoggedInOnlyView, PhotographerDetail):    

    model = models.Photographer
    template_name = "photographer/photographer_photos.html"

    def get_object(self, queryset=None):
        photographer = super().get_object(queryset=queryset)
        if photographer.zzigsa.pk != self.request.user.pk:
            raise Http404
        return photographer


@login_required
def delete_photo(request, photographer_pk, photo_pk):
    user = request.user
    try:
        photographer = models.Photographer.objects.get(pk=photographer_pk)
        if photographer.zzigsa.pk != user.pk:
            messages.error(request, "Can't delete that photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo deleted")
        return redirect(reverse("photographers:photos", kwargs={"pk": photographer_pk}))
    except models.Photographer.DoesNotExist:
        return redirect(reverse("core:home"))


class AddPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, FormView):

    template_name = "photographer/photo_create.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("photographers:photos", kwargs={"pk": pk}))


class ApplyZzigsaView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.ApplyZzigsaForm
    template_name = "photographer/zzigsa_create.html"

    def form_valid(self, form):
        photographer = form.save()
        photographer.zzigsa = self.request.user
        photographer.save()
        messages.success(self.request, "찍사 신청되었습니다")
        return redirect(reverse("photographers:detail", kwargs={"pk": photographer.pk}))

templates/photographer/detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{photographer.title}}</h2>
    <h3>{{photographer.zzigsa}}작가</h3>
    <h4>{{photographer.introduction}}</h4>
    <p>{{photographer.description}}</p>

{% endblock %}

templates/photographer/photo_create.html
include upload photo

templates/photographer/photographer_detail.html
{% extends 'base.html' %}

{% block content %}

    {% if photographer.zzigsa == user %}
    <a href="{% url 'photographers:edit' photographer.pk %}">Edit</a>

    {% endif %}

    <h2>{{photographer.title}}</h2>
    <h3>{{photographer.zzigsa}}작가</h3>
    <img src="{{photographer.profile.url}}" alt="">
    <h4>{{photographer.introduction}}</h4>
    <p>{{photographer.description}}</p>
    <p>사용 카메라: {{photographer.equip}}</p>
    <img src="{{photographer.equip.url}}" alt="">
    <p>작가 sns: {{photographer.sns}}</p>
    
    <!-- <div style="width: auto; height: auto; background-size: auto; background-image: url({{photographer.first_photo}}); "></div>
    {% for photo in photographer.get_next_four_photos %}
        <div style="width: auto; height: auto; background-image: url({{photo.file.url}});"></div>
    {% endfor %} -->

    <img src="{{photographer.first_photo}}">
    
    {% for photo in photographer.get_next_four_photos %}
    <img src="{{photo.file.url}}" alt="">

    {% endfor %}

    


{% endblock %}

templates/photographer/photographer_edit.html
{% extends 'base.html' %}

{% block content %}
 
    include 뭐시기

    <a href="{% url 'photographers:photos' photographer.pk %}">Edit Photos</a>

        
{% endblock %}

templates/photographer/photographer_list.html
{% extends 'base.html' %}

{% block content %}
    
    {% for photographer in photographers %}
        {% if photographer.zzigsa.zzigsa == "approved" %}
            <h1>
                <a href="{% url 'photographers:detail' photographer.pk %}">{{photographer.title}} - {{photographer.zzigsa}}작가</a>
            </h1>
            <img src="{{photographer.profile.url}}" alt="">
            <img src="{{photographer.first_photo}}" alt="">
        {% endif %}
            
    {% endfor %}
        
    <h5>
        
        {% if page.obj.has_previous %}
            <a href="?page={{page.obj.previous_page_number}">Previous</a>
        {% endif %}
        
        page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
        
        {% if page.obj.has_next %}
            <a href="?page={{page.obj.next_page_number}}">Next</a>
        {% endif %}
            
    </h5>

{% endblock content %}

templates/photographer/photographer_photos.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <a href="{% url 'photographers:add-photo' photographer.pk %}">Add Photo</a>
    <br>
    {% for photo in photographer.photos.all %}
        <img src="{{photo.file.url}}" alt="">
        <a href="{% url 'photographers:delete-photo' photographer.pk photo.pk %}">Delete</a>
    {% endfor %}
    <br>
    <a href="{% url 'photographers:edit' photographer.pk %}">Back to Edit page</a>

        
{% endblock %}

templates/photographer/zzigsa_create.html
{% extends 'base.html' %}

{% block content %}
 
    include 뭐시기

{% endblock %}