core/urls.py
from django.urls import path
from . import views
from photographer import views as photographer_views

app_name = "core"

urlpatterns = [
    path("", photographer_views.HomeView.as_view(), name="home")
]

photographer/urls.py
from django.urls import path
from . import views

app_name = "photographers"

urlpatterns = [
    path("create/", views.ApplyZzigsaView.as_view(), name="create"),
    path("<int:pk>", views.PhotographerDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditPhotographerView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.PhotographerPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:photographer_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo"),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>/", views.complete_verification, name="complete-verification"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePassword.as_view(), name="password"),
    path('<int:pk>/', views.UserProfileView.as_view(), name='profile'),
]

zzigsaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("user/", include("user.urls", namespace="user")),
    path("photographers/", include("photographer.urls", namespace="photographers")),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="/">찍사</a>
    
    <a href="{% url 'photographers:create' %}">Apply zzigsa</a>
    {% if user.is_authenticated %}
        
        <a href="{{user.get_absolute_url}}">Profile</a>
        <a href="{% url 'user:logout' %}">log out</a>
    {% else %}
        <a href="{% url 'user:login' %}">log in</a>
        <a href="{% url 'user:kakao-login' %}">kakao login</a>
        <a href="{% url 'user:signup' %}">sign up</a>
    {% endif %}

    {% block content %}
        
    {% endblock %}

</body>
</html>